// src/app/api/export/joint/mortise/route.ts
export const runtime="nodejs"; export const dynamic="force-dynamic";
type Units="mm"|"in"; type Host2D={name:string;thickness:number;length?:number;width?:number}; type Ins={name:string;thickness:number;length?:number;width?:number}; type MT={tenonThickness:number;tenonLength:number;shoulder?:number;haunch?:number;mortiseDepth?:number};
function parseSpecParam(raw:string){const t=raw.trim().replace(/^'+|'+$/g,"").replace(/^"+|"+$/g,"");try{return JSON.parse(t);}catch{}try{return JSON.parse(decodeURIComponent(t));}catch{} throw new Error("Bad ?spec; starts with: "+t.slice(0,40));}
function dimLinePx(x1:number,y1:number,x2:number,y2:number,label:string,fontPx:number,color="#555"){const dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len;const tick=Math.min(18,Math.max(10,len*0.08));const ax1x=x1+ux*tick,ax1y=y1+uy*tick,ax2x=x2-ux*tick,ax2y=y2-uy*tick;const off=12,lx=(x1+x2)/2-uy*off,ly=(y1+y2)/2+ux*off;return `
  <g stroke="${color}" fill="none" stroke-width="${Math.max(1.2,len*0.02)}"><line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" /></g>
  <text x="${lx}" y="${ly}" font-size="${fontPx}" text-anchor="middle" dominant-baseline="middle" fill="#111" stroke="#fff" stroke-width="${Math.max(2.5,fontPx*0.22)}" paint-order="stroke">${label}</text>`;}
export async function GET(req:Request){try{const url=new URL(req.url);const raw=url.searchParams.get("spec");if(!raw)return new Response("Missing ?spec",{status:400});const wpx=Math.min(1400,Math.max(480,Number(url.searchParams.get("w")||900)));const fontPx=Math.min(28,Math.max(12,Number(url.searchParams.get("font")||18)));const showTitle=url.searchParams.get("title")!=="0";
  const spec=parseSpecParam(raw) as {units:Units;host:Host2D;insert:Ins;mt:MT;hostEdge?:"N"|"S"|"E"|"W";width?:number};const units=spec.units||"mm";const labelU=(v:number)=>`${v}${units==="mm"?" mm":" in"}`;
  const boardH=Math.max(160,Math.round(fontPx*8)),boardW=Math.max(280,Math.round(fontPx*14)),titleH=showTitle?Math.max(36,fontPx+12):Math.max(10,fontPx/2),footerH=Math.max(30,fontPx+6),viewW=wpx,viewH=titleH+boardH+footerH;const bx=(viewW-boardW)/2,by=titleH,bw=boardW,bh=boardH;
  const unitsToPx=(boardH*0.7)/Math.max(spec.host.thickness||18,1);const mDepth=(spec.mt.mortiseDepth??spec.mt.tenonLength),mWidth=spec.width??(spec.insert.width??60);const mdPx=Math.max(12,Math.min(boardH*0.5,mDepth*unitsToPx)), mwPx=Math.max(18,Math.min(boardW*0.65,mWidth*unitsToPx));
  const edge=spec.hostEdge??"N"; let mx=0,my=0,mw=0,mh=0; if(edge==="N"){mx=bx+(bw-mwPx)/2;my=by;mw=mwPx;mh=mdPx;} else if(edge==="S"){mx=bx+(bw-mwPx)/2;my=by+bh-mdPx;mw=mwPx;mh=mdPx;} else if(edge==="E"){mx=bx+bw-mdPx;my=by+(bh-mwPx)/2;mw=mdPx;mh=mwPx;} else {mx=bx;my=by+(bh-mwPx)/2;mw=mdPx;mh=mwPx;}
  const title=`Mortise — ${spec.host.name} for ${spec.insert.name} (${units})`;
  const svg=`<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${viewW} ${viewH}" width="${viewW}" height="${viewH}"><style>.board{fill:#fafafa;stroke:#999;stroke-width:1.5}.cut{fill:#ffece6;stroke:#e11d48;stroke-width:2}.lbl{font-size:${fontPx}px;fill:#111;font-weight:700;font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Arial}.tiny{font-size:${Math.max(13,fontPx-3)}px;fill:#333}</style>
  ${showTitle?`<text class="lbl" x="${viewW/2}" y="${Math.max(fontPx+8,titleH*0.65)}" text-anchor="middle">${title}</text>`:""}<rect class="board" x="${bx}" y="${by}" width="${bw}" height="${bh}"/><rect class="cut" x="${mx}" y="${my}" width="${mw}" height="${mh}"/>
  ${edge==="N"||edge==="S"?dimLinePx(mx,my+mh+26,mx+mw,my+mh+26,"Width: "+labelU(mWidth),fontPx):dimLinePx(mx-26,my,mx-26,my+mh,"Width: "+labelU(mWidth),fontPx)}
  ${edge==="N"||edge==="S"?dimLinePx(mx-26,my,mx-26,my+mh,"Depth: "+labelU(mDepth),fontPx):dimLinePx(mx,my+mh+26,mx+mw,my+mh+26,"Depth: "+labelU(mDepth),fontPx)}
  <text class="tiny" x="${bx+bw}" y="${by+bh+Math.max(18,fontPx)}" text-anchor="end">Tenon t=${labelU(spec.mt.tenonThickness)} • len=${labelU(spec.mt.tenonLength)} • shoulder=${labelU(spec.mt.shoulder??0)}</text></svg>`;
  return new Response(svg,{headers:{"Content-Type":"image/svg+xml","Cache-Control":"no-store"}});}catch(e:any){return new Response("Mortise plate error: "+(e?.message||String(e)),{status:400});}}
